export const projects = [
  {
    title: 'Acebook',
    description: "Social media app inspired by Facebook. Comments and likes functionality along with personal user 'wall' (profile)...",
      image: '/images/5.png',
      tags: ['Mongo', 'Express', 'React', 'Node'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 0,
  },
  {
    title: 'Sweepstake',
    description:"A webapp that allows the user to create a sweepstake from a current football competition ie AFCon. Premier League..",
    image: '/images/6.png',
    tags: ['React', 'JavaScript'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 1,
  },
  {
    title: 'React Blog',
    description: "Single page webapp that allows the user to create a blog post and attribute a name to that post.",
      image: '/images/7.png',
      tags: ['React', 'WebRTC'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 2,
  },
  {
    title: 'Tech Test: Bank',
    description: "Single page webapp that allows the user to create a blog post and attribute a name to that post",
    image: '/images/8.png',
    tags: ['React', 'ChatEngine', 'Firebase'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 3,
  },
  {
    title: 'Weather App',
    description: "An app that lets you see what the weather is in a city of your choosing by typing it into the search bar. Used an external API",
    image: '/images/9.png',
    tags: ['React', 'ChatEngine', 'Firebase'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 3,
  },
];

export const TimeLineData = [
  { year: 2022, text: 'Started my journey', },
  { year: 2018, text: 'Worked as a freelance developer', },
  { year: 2019, text: 'Founded JavaScript Mastery', },
  { year: 2020, text: 'Shared my projects with the world', },
  { year: 2021, text: 'Started my own platform', },
];